services:

  o2p-postgis:
    container_name: o2p-postgis
    image: kartoza/postgis:16-3.4
    profiles: ["db", "all"]
    environment:
      PASSWORD_AUTHENTICATION: md5
      RUN_AS_ROOT: false
      ALL_DATABASES: true
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
      SHARED_PRELOAD_LIBRARIES: pg_cron
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: o2p
      POSTGRES_USER: o2p
      POSTGRES_PASS: o2p
      POSTGRES_INITDB_ARGS: "-c shared_buffers=1GB -c work_mem=50MB -c maintenance_work_mem=10GB -c autovacuum_work_mem=2GB -c wal_level=minimal -c checkpoint_completion_target=0.9 -c max_wal_senders=0 -c random_page_cost=1.0"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - o2p-network
        
  o2p-osm2pgsql:
    container_name: o2p-osm2pgsql
    profiles: ["osm", "all"]
    image: osm2pgsql-iboates:latest
    environment:
      PGHOST: o2p-postgis
      PGDATABASE: o2p
      PGUSER: o2p
      PGPASSWORD: o2p
      PGPORT: 5432
    depends_on:
      - o2p-postgis
    volumes:
      - ./data/osm:/data
    restart: always
    networks:
      - o2p-network

volumes:
  postgis_data:

networks:
  o2p-network:
    name: o2p
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.70.0/24